<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title">Add Collection</h3>
  </div><!-- /.box-header -->          
    <?= $this->tag->form(array("Collections/Add/".$id, "method"=>"post" )) ?>
 
  <div class="box-body">  
    
     
    <div class="form-group">
      <label for="collection_name">Collection Name</label>
      <input type="text" name="collection_name" class="form-control" id="collectionInput" placeholder="Collection" value="<?PHP echo $collection_name;?>">
    </div>     

  </div><!-- /.box-body -->

  <div class="box-footer">
    <button type="submit" class="btn btn-primary">Save</button>
  </div>
  </form>
</div><!-- /.box -->