<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title">Edit Collection</h3>
  </div><!-- /.box-header -->          
    <?= $this->tag->form(array("Collections/Edit/".$itemID, "method"=>"post" )) ?>
 <input type="hidden" name="itemID" value="<?PHP echo $itemID;?>" />
   
  <?PHP  //print_r($values);
    //echo "<pre>";print_r($data);
	$collection_name = $data['collection']; 
  ?>
  <div class="box-body">  
    
     
    <div class="form-group">
      <label for="collection_name">Collection Name</label>
      <input type="text" name="collection_name" class="form-control" id="collectionInput" placeholder="Collection" value="<?PHP echo $collection_name;?>">
    </div>     

  </div><!-- /.box-body -->

  <div class="box-footer">
    <button type="submit" class="btn btn-primary">Save</button>
  </div>
  </form>
</div><!-- /.box -->