<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title">Add Contact Details</h3>
  </div><!-- /.box-header -->          
  
  <?= $this->tag->form(array("item/contact/".$id, "method"=>"post", "enctype"=>"multipart/form-data")) ?>
 
      
  <div class="box-body">  
    
    <div class="form-group">
      <label for="meetingNumber">Contribution Author</label>
      <input type="text" name="author" class="form-control" id="authorInput" placeholder="Author" value="<?PHP echo $this->session->get('auth')['user_type'];?>" readonly>
    </div>
  <div class="form-group">
      <label for="title">First Name</label>
      <input type="text" name="firstname" class="form-control" id="FirstnameInput" placeholder="First Name"  value="<?PHP echo $firstname;?>">
    </div>
  <div class="form-group">
      <label for="title">Last Name</label>
      <input type="text" name="lastname" class="form-control" id="LastnameInput" placeholder="Last Name"  value="<?PHP echo $lastname;?>">
    </div>  
    <div class="form-group">
      <label for="title">Title</label>
      <input type="text" name="title" class="form-control" id="titleInput" placeholder="Meeting Title" value="<?PHP echo $title;?>">
    </div>    
    <div class="form-group">
      <label for="title">Treaty</label>
      <input type="text" name="treaty" class="form-control" id="treatyInput" placeholder="Treaty"  value="<?PHP echo $treaty;?>">
    </div>
  <div class="form-group">
      <label for="title">Country</label>
      <input type="text" name="country" class="form-control" id="CountryInput" placeholder="Country"  value="<?PHP echo $country;?>">
    </div>  
    <div class="form-group">
      <label for="title">Prefix</label>
      <input type="text" name="prefix" class="form-control" id="prefixInput" placeholder="Prefix"  value="<?PHP echo $prefix;?>">
    </div>
  <div class="form-group">
      <label for="title">Type</label>
      <input type="text" name="type" class="form-control" id="TypeInput" placeholder="Type" value="<?PHP echo $type;?>">
    </div>
  <div class="form-group">
      <label for="title">Position</label>
      <input type="text" name="position" class="form-control" id="PositionInput" placeholder="Position"  value="<?PHP echo $position;?>">
    </div>    
  <div class="form-group">
      <label for="title">Organizations</label>
      <input type="text" name="organizations" class="form-control" id="OrganizationsInput" placeholder="Organizations"  value="<?PHP echo $organizations;?>">
    </div>
    <div class="form-group">
      <label for="title">Department</label>
      <input type="text" name="department" class="form-control" id="DepartmentInput" placeholder="Department"  value="<?PHP echo $department;?>">
    </div>  
  
    <div class="form-group">
      <label for="title">Location</label>
      <input type="text" name="location" class="form-control" id="LocationInput" placeholder="Location"  value="<?PHP echo $location;?>">
    </div>
  <div class="form-group">
      <label for="title">Email</label>
      <input type="text" name="email" class="form-control" id="EmailInput" placeholder="Email"  value="<?PHP echo $email;?>">
    </div>
  <div class="form-group">
      <label for="title">Phone</label>
      <input type="text" name="phone" class="form-control" id="phoneInput" placeholder="Phone"  value="<?PHP echo $phone;?>">
    </div>
  <div class="form-group">
      <label for="title">Fax</label>
      <input type="text" name="fax" class="form-control" id="FaxInput" placeholder="Fax"  value="<?PHP echo $fax;?>">
    </div>
  <div class="form-group" 
      <label for="title">Status</label>
      <input type="text" name="status" class="form-control" id="StatusInput" placeholder="Status"  value="<?PHP echo $status;?>">
    </div>   

  </div><!-- /.box-body -->

  <div class="box-footer">
    <button type="submit" class="btn btn-primary">Save</button>
  </div>
  </form>
</div><!-- /.box -->