<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title">Add Publication Details</h3>
  </div><!-- /.box-header -->


  
  <?= $this->tag->form(array("item/publication/".$id, "method"=>"post", "enctype"=>"multipart/form-data")) ?>
  
  <div class="box-body">  
    
    <div class="form-group">
      <label for="exampleInputEmail1">Title</label>
      <input type="text" name="title" class="form-control" id="titleInput" placeholder="Document Title">
    </div>

    <div class="form-group">
      <label for="meetingNumber">Publication Year</label>
      <input type="text" name="year" class="form-control" id="publicationInput" placeholder="Publication Year">
    </div>

    <div class="form-group">
      <label for="title">Keywords</label>
      <input type="text" name="keywords" class="form-control" id="keywordsInput" placeholder="Decision Keywords">
    </div>

    <div class="form-group">
      <label>Description</label>
      <textarea name="description" class="form-control" rows="3" placeholder="Description ..."></textarea>
    </div>
                    
    <div class="form-group">
      <label for="exampleInputFile">File input</label>
      <input type="file" id="documentFile" name="fileOne">
      <p class="help-block">Upload the relevant file.</p>
    </div>

  </div><!-- /.box-body -->

  <div class="box-footer">
    <button type="submit" class="btn btn-primary">Save</button>
  </div>
  </form>
</div><!-- /.box -->