<script type="text/javascript">
   
	$(document).ready(function() {
		 
  
		var table_data = <?PHP echo $data; ?>; 

		console.log(table_data);

		var table_options = {       
		  "processing": true,  
		  "rowId": 'id',
		  "autoWidth": false, 
		  "bSort": true, 
		  "data": table_data,
		  "columns": [
              {
                  "title": "ID",
                  "data": "id"
              },
                {
                    "title": "Meeting Title",
                    "data": "meetingTitle"
                },
                {
                    "title": "Treaty",
                    "data": "treaty"
                },
                {   "title": "Type",
                    "data": "type"
                },
              {
                  "title": "Author",
                  "data": "author"
              },
              {
                  "title": "Updated",
                  "data": "updated"
              },
		    //{
			//    "title": "",
			//    "class": "",
			//    "targets": 1,
			//    "width": "10px",
			//    "orderable": false,
			//    "data": "id",
			//    "defaultContent": "",
	    	//	render: function ( data, type, row ) {
			//        if ( type === 'display' ) {
			//           return '<p><a href="<?//=$this->url->get("item/detail/");?>//'+ data +'"><span class="glyphicon glyphicon-new-window"></span></a></p>';
			//        }
		    //
		    //    	return data;
	        //	},
	        //},
		  ],
		//"columnDefs":[
		//{
		//	"render": function ( data, type, row )
		//	{
		//		if(data == ''){ data = 'No Title';}
		//
		//		var title = '<a href="<?//=$this->url->get("item/detail/");?>//'+ row.id +'" > '+ data +' </a>' ;
        //
		//		return title;
		//	},
		//	"targets": [0]
		//},
		//]
		};

		  
		var documents_categories_table = $('#document-categories-table').DataTable(table_options);   
		
		$('#document-categories-table').on( 'dblclick', 'tr', function () {
		    
		    var id = 109;
		    window.location = "/dspace-client/item/detail/"+id;
		});

		

	});


</script>