<div class="box box-primary">
  <div class="box-header with-border"> 
  </div><!-- /.box-header -->          
    <?= $this->tag->form(array("Questions/Edit/".$itemID, "method"=>"post", "role"=>"form", "class"=>"form-horizontal ajax-submit" )) ?>
 <input type="hidden" name="itemID" value="<?PHP echo $itemID;?>" />
 
  <?PHP  //print_r($values);
    // echo "<pre>";print_r($data);
	$questions_title = $data['questions_title']; 
	$questions_name = $data['questions_name']; 
	$control_type = $data['control_type']; 
	$lookup_table = $data['lookup_table']; 
	$required = $data['required']; 
  ?>
  <div class="box-body">  
    
    <div class="form-group"> 		
      <label for="questions_title"  class="col-md-2 control-label">Question Title</label>
	  <div class="col-md-8"> 
		<input type="text" name="questions_title" class="form-control" id="questionsInput" placeholder="Questions Title" value="<?PHP echo $questions_title;?>"> 
	  </div>
    </div>  
    <div class="form-group">
      <label for="questions_name"  class="col-md-2 control-label">Question Name</label>
       <div class="col-md-8">
			<input type="text" name="questions_name" class="form-control" id="questionsInput" placeholder="Questions" value="<?PHP echo $questions_name;?>">
	   </div>
    </div>     
	<div class="form-group"> 
      <label for="questions_name" class="col-md-2 control-label">Control Type</label>
	   <div class="col-md-8">
		   <select name="control_type" id="control_type" class="form-control">
			<option value="">--Control Type--</option>
			<option value="checkbox" <?PHP if($control_type == "checkbox"){echo "selected";}?>>checkbox</option>
			<option value="dropdown" <?PHP if($control_type == "dropdown"){echo "selected";}?>>dropdown</option>
			<option value="radiobutton" <?PHP if($control_type == "radiobutton"){echo "selected";}?>>radiobutton</option>
			<option value="teaxtarea" <?PHP if($control_type == "teaxtarea"){echo "selected";}?>>teaxtarea</option>
			<option value="textbox" <?PHP if($control_type == "textbox"){echo "selected";}?>>textbox</option>
		  </select>
		</div>
  </div>
  <div class="form-group">
      <label for="lookup_table"  class="col-md-2 control-label">Lookup Table</label>
       <div class="col-md-8">
			<input type="text" name="lookup_table" class="form-control" id="lookup_tableInput" placeholder="Lookup Table" value="<?PHP echo $lookup_table;?>">
	   </div>
    </div>
  <div class="form-group">
      <label for="required"  class="col-md-2 control-label">Required</label>
       <div class="col-md-8">
			<input type="text" name="required" class="form-control" id="requiredInput" placeholder="Required" value="<?PHP echo $required;?>">
	   </div>
    </div>
	<div class="form-group">
		<div class="col-md-offset-2 col-md-10">
			<button type="submit" id="submit" class="btn  btn-primary"> Save</button>
		</div>
	</div>
  <div class="box-footer"> 
  </div>
  </form>
</div><!-- /.box -->