<div class="box box-primary">
  <div class="box-header with-border"> 
  </div><!-- /.box-header -->                
  <?PHP  //print_r($values);
    // echo "<pre>";print_r($data);
	$username = $user_details['username']; 
	$name = $user_details['name']; 
	$email = $user_details['email']; 
	$active = $user_details['active'];    
	
  ?>
  <?= $this->tag->form(array("user/".$action."/".$itemID, "method"=>"post", "enctype"=>"multipart/form-data", "role"=>"form", "class"=>"form-horizontal ajax-submit" )) ?>
  <div class="box-body">  
	<div class="form-group">
      <label for="username"  class="col-md-4 control-label">Username</label>
       <div class="col-md-8"> 
			<input type="text" name="username" class="form-control" id="username" placeholder="Username" value="<?PHP echo $username;?>">
	   </div>
    </div>
	<div class="form-group">
      <label for="name"  class="col-md-4 control-label">Name</label>
       <div class="col-md-8"> 
			<input type="text" name="name" class="form-control" id="name" placeholder="Name" value="<?PHP echo $name;?>">
	   </div>
    </div>
	<div class="form-group">
      <label for="email"  class="col-md-4 control-label">Email</label>
       <div class="col-md-8"> 
			<input type="text" name="email" class="form-control" id="email" placeholder="Email" value="<?PHP echo $email;?>">
	   </div>
    </div>
	<div class="form-group"> 
      <label for="active" class="col-md-4 control-label">Active</label>
	   <div class="col-md-8">
		   <select name="active" id="active" class="form-control col-md-4">
			<option value="">--Active--</option>
			<option value="1" <?PHP if($active == "1"){echo "selected";}?>>YES</option>
			<option value="0" <?PHP if($active == "0"){echo "selected";}?>>NO</option>			 
		  </select>
		</div>
  </div>
	<div class="form-group"> 
      <label for="user_group" class="col-md-4 control-label">User Group</label>
	   <div class="col-md-8"> 
		   <select name="user_group[]" id="user_group" multiple class="form-control col-md-4"> 
			<?PHP 
				for($i = 0; $i < count($user_groups_data); $i++)
				{
				$id = $user_groups_data[$i]['id'];
				echo '<option value="'.$id.'"';
				for($j = 0; $j < count($user_group_mapping); $j++)
				{
					if($id == $user_group_mapping[$j]['id']){echo "selected";}
				}
				  // $is_selected = in_array($user_groups_data[$i]['id'], $user_group_mapping['id']) ? 'selected' : false ; echo $is_selected;   
				  
				 echo " >".$user_groups_data[$i]['name']."</option>"; 
				} ?>
			 
		  </select>
		</div>
  </div>
  
  </div><!-- /.box-body -->

  <div class="box-footer">
    <button id="btnSubmit" type="submit" class="btn  btn-primary ajax-submit" >Save</button>
  </div>
  </form>
</div><!-- /.box -->