<script type="text/javascript">
   
	$(document).ready(function() {
		 
  
		var table_data = <?PHP echo $data; ?>; 

		console.log(table_data);

		var table_options = {       
		  "processing": true,  
		  "rowId": 'id',
		  "autoWidth": false, 
		  "bSort": true, 
		  "data": table_data,
		  "columns": [      
		    { 
		    	"title": "Name", 
		    	"data": "name"
		    },
			{ 
		    	"title": "Email", 
		    	"data": "email"
		    }, 
			{ 
		    	"title": "Active", 
		    	"data": "active"
		    }, 
		    { "title": "Created", "data": "lastModified"},
		    { 
			    "title": "Edit", 
			    "class": "", 
			    "targets": 1, 
			    "width": "10px",
			    "orderable": false,
			    "data": "id",
			    "defaultContent": "",
	    		render: function ( data, type, row ) {
			        if ( type === 'display' ) {
			           return '<p><a href="<?=$this->url->get("user/Edit/");?>'+ data +'" itemid="'+ row.id +'" ><span class="glyphicon glyphicon-edit edit"  itemid="'+ row.id +'"></span></a></p>';
					   
			        }
		        
		        	return data;
	        	},
	        }, 
		  ],
		"columnDefs":[		
		{
			"render": function ( data, type, row ) 
			{
				if(data == ''){ data = 'No Title';}
				
				var title = '<a href="<?=$this->url->get("user/Edit/");?>'+ row.id +'"> '+ data +' </a>' ;

				return title;
			},
			"targets": [0]
		},
		]
		};

		  
		var documents_questions_table = $('#document-users-table').DataTable(table_options);   
		
		$('#document-users-table').on( 'dblclick', 'tr', function () {
		    
		    var id = 109;
		    window.location = "/users/Edit/"+id;
		});
		
		
		$('body').on('click', '.edit', function(event) {
		
		var id = $(this).attr('itemid');

		$.ajax( "<?=$this->url->get("user/edit/");?>/"+id )
			.done(function(resp) {
				body = resp ;
				if( resp.code == 0 )
				{
					body = '<p class="text-center text-error">' + resp.text + '</p>';
				}
				show_popup('User Details', body, '', 'modal-dialog');
			})
			.fail(function() {
				body = 'Error loading User Details form';
				show_popup('User Details', body, '', 'modal-dialog');
			});
		event.preventDefault();
		return false;

		//show_popup(title, body, footer, modalsize)

	}); 
	
		$('body').on('submit', '.ajax-submit', function(event) 
		{

        var options = {
            dataType: 'json',
            success:    function(resp) {

                if( resp.code == 1 )
                {
                    $('#default-modal .modal-footer').html('<p class="text-center text-success">' + resp.text + '</p>').fadeIn();
                        if(resp.action == 'add')
                        {
                            $(':input','#frm_answers')
                            .not(':button, :submit, :reset, :hidden')
                            .val('');
                            
                            
                            $('#name').focus();

                            setTimeout(function(){
                                $( "p" ).empty();
                            }, 5000);
                        }
                        else
                        {
                            new $.flavr({ content: resp.text, buttons: false, autoclose: true, timeout: 3000 }); 
                            $('#default-modal').modal('hide');
                        }

                    location.reload();
                }
                else
                {
                    $('#default-modal .modal-footer').html('<p class="text-center text-danger">' + resp.text + '</p>').fadeIn();;
                }
            }
        };

        $(this).ajaxSubmit(options);
        // return false to prevent normal browser submit and page navigation 
        event.preventDefault();
        return false;

    });

	});


</script>