<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title">Edit Metadata</h3>
  </div><!-- /.box-header -->          
    <?= $this->tag->form(array("Metadata/Edit/".$itemID, "method"=>"post" )) ?>
 <input type="hidden" name="itemID" value="<?PHP echo $itemID;?>" />
   
  <?PHP  //print_r($values);
    // echo "<pre>";print_r($data);
	$metadata_name = $data['metadata_name']; 
  ?>
  <div class="box-body">  
    
     
    <div class="form-group">
      <label for="metadata_name">Metadata Name</label>
      <input type="text" name="metadata_name" class="form-control" id="metadataInput" placeholder="Metadata" value="<?PHP echo $metadata_name;?>">
    </div>     

  </div><!-- /.box-body -->

  <div class="box-footer">
    <button type="submit" class="btn btn-primary">Save</button>
  </div>
  </form>
</div><!-- /.box -->