<!-- Not in Use - Use layout.phtml-->
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>INFORMEA Repository</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.5 --> 
    <?= $this->tag->stylesheetLink("bootstrap/css/bootstrap.min.css"); ?>
    <!-- Font Awesome >
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Ionicons >
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css"---->
    <!-- Theme style -->
    <?= $this->tag->stylesheetLink("css/AdminLTE.min.css"); ?>
    <!-- AdminLTE Skins. Choose a skin from the css/skins folder instead of downloading all of them to reduce the load. -->
    <?= $this->tag->stylesheetLink("css/skins/_all-skins.min.css"); ?>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <!-- ADD THE CLASS layout-top-nav TO REMOVE THE SIDEBAR. -->
  <body class="hold-transition skin-blue layout-top-nav">
    <div class="wrapper">

      <header class="main-header">
        <nav class="navbar navbar-static-top">
          <div class="container">
            <div class="navbar-header">
              <a href="#" class="navbar-brand"><b>INFO MEA </b>Repository</a>
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
                <i class="fa fa-bars"></i>
              </button>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse pull-left" id="navbar-collapse">
              <ul class="nav navbar-nav">
                <li class="active"><a href="#">Search <span class="sr-only">(current)</span></a></li>                
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Categories <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><?= $this->tag->linkTo("category/list/4", "Meetings"); ?></li>
                    <li><?= $this->tag->linkTo("category/list/3", "Decisions"); ?></li>
                    <li><?= $this->tag->linkTo("category/list/2", "Contacts"); ?></li>                    
                    <li><?= $this->tag->linkTo("category/list/1", "Technical Reports"); ?></li>                  
                  </ul>
                </li>
              </ul>              
            </div><!-- /.navbar-collapse -->

            <!-- Navbar Right Menu -->
              <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                  
                  <!-- User Account Menu -->
                  <li class="dropdown user user-menu">
                    <!-- Menu Toggle Button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      <!-- The user image in the navbar-->
                      <!-- <img src="img/user2-160x160.jpg" class="user-image" alt="User Image">-->                      
                      <?= $this->tag->image(array("img/user2-160x160.jpg", "alt" =>"User Image", "class"=>"user-image")); ?>
                      <!-- hidden-xs hides the username on small devices so only the image appears. -->
                      <span class="hidden-xs">Yonny Owuor</span>
                    </a> 
                    <ul  class="dropdown-menu">
                      <li class="user-footer">
                      <div class="pull-left">
                        <!--<a href="#" class="btn btn-default btn-flat">Profile</a>-->
                      </div>
                      <div class="pull-right">                        
                        <?= $this->tag->linkTo(array('user/logout', 'Sign Out', 'class' => 'btn btn-default btn-flat')) ?>
                      </div>
                    </li>
                  </ul>                   
                  </li>
                </ul>
              </div><!-- /.navbar-custom-menu -->
          </div><!-- /.container-fluid -->
        </nav>
      </header>
      <!-- Full Width Column -->
      <div class="content-wrapper">
        <div class="container">
          <!-- Content Header (Page header) -->
          <section class="content-header">
            <h1><?= $title ?></h1>
            <!--<ol class="breadcrumb">
              <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
              <li><a href="#">Layout</a></li>
              <li class="active">Top Navigation</li>
            </ol>-->
          </section>

          <!-- Main content -->
          <section class="content">


              <?php print $this->getContent(); ?>

            
          </section><!-- /.content -->

        </div><!-- /.container -->
      </div><!-- /.content-wrapper -->
      <footer class="main-footer">
        <div class="container">
          <div class="pull-right hidden-xs">
            <b>Version</b> 1.0
          </div>
          <strong>Copyright &copy; 2016 <a href="#">UNEP ICTU</a>.</strong> All rights reserved.
        </div><!-- /.container -->
      </footer>
    </div><!-- ./wrapper -->

    <!-- jQuery 2.1.4 -->
    <?= $this->tag->javascriptInclude("plugins/jQuery/jQuery-2.1.4.min.js") ?>
    <!-- Bootstrap 3.3.5 -->
    <?= $this->tag->javascriptInclude("bootstrap/js/bootstrap.min.js") ?>
    <!-- SlimScroll -->
    <?= $this->tag->javascriptInclude("plugins/slimScroll/jquery.slimscroll.min.js") ?>
    <!-- FastClick -->
    <?= $this->tag->javascriptInclude("plugins/fastclick/fastclick.min.js") ?>
    <!-- AdminLTE App -->
    <?= $this->tag->javascriptInclude("js/app.min.js") ?>
    <!-- AdminLTE for demo purposes -->
    <?= $this->tag->javascriptInclude("js/demo.js") ?>
  </body>
</html>
