<!-- <section class="content-header">
	<h1>
		<i class = "fa fa-database"></i>&nbsp;DATACENTER
	</h1>
</section> -->
<div class = "content-body">
	<div class = "row">
		<div class="col-md-4 col-sm-6 col-xs-12">
			<a href = "#">
				<div class="small-box bg-green">
					<div class="inner">
						<h3>Download Data</h3>

						<p>From DSPACE</p>
					</div>
					<div class="icon">
						<i class="ion ion-ios-cloud-download"></i>
					</div>
				</div>
			</a>
			<!-- /.info-box -->
		</div>
		<div class="col-md-4 col-sm-6 col-xs-12">
			<a href = "#">
				<div class="small-box bg-red">
					<div class="inner">
						<h3>Upload Data</h3>

						<p>To DSPACE</p>
					</div>
					<div class="icon">
						<i class="ion ion-ios-cloud-upload"></i>
					</div>
				</div>
			</a>
			<!-- /.info-box -->
		</div>
	</div>
</div>